-- Init sql

-- Базовая настройка для новых баз

\c template1

CREATE EXTENSION IF NOT EXISTS "intarray";
CREATE EXTENSION IF NOT EXISTS "ltree";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "hstore";

CREATE OPERATOR CLASS _uuid_ops DEFAULT
    FOR TYPE _UUID USING GIN AS
    OPERATOR 1 &&( ANYARRAY, ANYARRAY ),
    OPERATOR 2 @>( ANYARRAY, ANYARRAY ),
    OPERATOR 3 <@( ANYARRAY, ANYARRAY ),
    OPERATOR 4 =( ANYARRAY, ANYARRAY ),
    FUNCTION 1 uuid_cmp( UUID, UUID ),
    FUNCTION 2 ginarrayextract( ANYARRAY, INTERNAL, INTERNAL ),
    FUNCTION 3 ginqueryarrayextract( ANYARRAY, INTERNAL, SMALLINT, INTERNAL, INTERNAL, INTERNAL, INTERNAL ),
    FUNCTION 4 ginarrayconsistent( INTERNAL, SMALLINT, ANYARRAY, INTEGER, INTERNAL, INTERNAL, INTERNAL, INTERNAL ),
    STORAGE UUID;

-- TODO: Change password to more strong
CREATE ROLE puser WITH LOGIN ENCRYPTED PASSWORD '2580';

CREATE DATABASE puser WITH OWNER puser;

CREATE DATABASE pluto_api WITH OWNER puser;
